### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2588' in position 0: ordinal not in range(256)

### ISSUE THREAD

**Issue by w1d2s** [rakeshvar/rnn_ctc#13]
Hello, I ran 'python3 gen_data.py data.pkl' and had error messages as follow:

```
(0, 1, 2)  !"
 0¦              Traceback (most recent call last):
  File "gen_data.py", line 27, in <module>
    utils.slab_print(x)
  File "/home/speech/wudan14/rnn_ctc-master/utils.py", line 20, in slab_print
    elif val <= 1.:  print('\u2588', end=''),
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2588' in position 0: ordinal not in range(256)
```

how can i solve this problem?

**Comment by rakeshvar** [comment]
Set the following environmental variables. This will enable you to print unicode to terminal.

``` sh
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```

You can add the above three lines to your `.bashrc` file.
